In [71]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

print('Libraries imported.')

Libraries imported.

In [72]:
df = pd.read_csv('toronto2.csv',header=None)
df.columns=["Postalcode","Borough","Neighbourhood"]
indexNames = df[ df['Borough'] =='Not assigned'].index
df.drop(indexNames , inplace=True)
df.loc[df['Neighbourhood'] =='Not assigned' , 'Neighbourhood'] = df['Borough']
result = df.groupby(['Postalcode','Borough'], sort=False).agg( ', '.join)
df_new=result.reset_index()
df_new.head(15)

   Postalcode           Borough                                      Neighbourhood
0    Postcode           Borough                                      Neighbourhood
1         M3A        North York                                          Parkwoods
2         M4A        North York                                   Victoria Village
3         M5A  Downtown Toronto                          Regent Park, Harbourfront
4         M6A        North York                   Lawrence Manor, Lawrence Heights
5         M7A  Downtown Toronto        Queen's Park, Ontario Provincial Government
6         M9A         Etobicoke            Islington Avenue, Humber Valley Village
7         M1B       Scarborough                                     Malvern, Rouge
8         M3B        North York                                          Don Mills
9         M4B         East York                    Parkview Hill, Woodbine Gardens
10        M5B  Downtown Toronto                           Garden District, Ryerson
11        M6B        North York                                          Glencairn
12        M9B         Etobicoke  West Deane Park, Princess Gardens, Martin Grov...
13        M1C       Scarborough             Rouge Hill, Port Union, Highland Creek
14        M3C        North York                                          Don Mills

In [73]:
df_lon_lat = pd.read_csv('Geospatial_Coordinates.csv')
df_lon_lat.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [75]:
df_lon_lat.columns=['Postalcode','Latitude','Longitude']
df_lon_lat.head()

  Postalcode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In [76]:
Toronto_df = pd.merge(df_new,
                 df_lon_lat[['Postalcode','Latitude', 'Longitude']],
                 on='Postalcode')
Toronto_df.head()

  Postalcode           Borough                                Neighbourhood   Latitude  Longitude
0        M3A        North York                                    Parkwoods  43.753259 -79.329656
1        M4A        North York                             Victoria Village  43.725882 -79.315572
2        M5A  Downtown Toronto                    Regent Park, Harbourfront  43.654260 -79.360636
3        M6A        North York             Lawrence Manor, Lawrence Heights  43.718518 -79.464763
4        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government  43.662301 -79.389494